require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.3

# Lint
Lint/AssignmentInCondition:
  Enabled: false

# Metrics
Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

# Style
Style/Documentation:
  Enabled: false
