version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/avatar-service
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
    - checkout

    # Prepare for artifact and test results
    - run: mkdir -p $CIRCLE_TEST_REPORTS

    # Update rubygems
    - run: gem update --system

    # Restore the dependency cache
    - restore_cache:
        keys:
          - avatar-service-v1-{{ checksum "Gemfile.lock" }}
          - avatar-service-v1-

    # Install gems
    - run: bundle check || bundle install --path vendor/bundle

    # Save dependency cache
    - save_cache:
        key: avatar-service-v1-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

    # Test
    - run: mkdir -p $CIRCLE_TEST_REPORTS/rspec
    - run:
        command: bundle exec rspec --color --format documentation --require spec_helper --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/rspec.xml --format progress spec

    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
